language: node_js

node_js:
- 8

before_install:
- npm install -g gulp

install:
- npm install

before_script:
- git config --global user.name 'yangmingming'
- git config --global user.email 'hzyangmingming@corp.netease.com'

script:
- npm run build